import type { Metadata } from "next";
import { Inter } from 'next/font/google'; //Import global font
import '../styles/main.scss'; //Import global styles
import Navbar from "@components/navigation/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  variable: '--font-inter',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
