import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import '@styles/main.scss';
import Navbar from "@components/navigation/navbar";
import { AuthProvider } from '@context/auth';
import VerifyEmailBanner from "@components/banners/verify-email";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  variable: '--font-inter',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <VerifyEmailBanner />
          {children}
          <div id="modal-root"></div>
        </AuthProvider>
      </body>
    </html>
  );
}
