name: Build and Deploy Next.js App to S3

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint (non-blocking)
        run: npm run lint || true

      - name: Build Next.js App
        run: npm run build

      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-2'

      - name: Set Bucket Name
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "BUCKET_NAME=nessi-webapp-dev-${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "BUCKET_NAME=nessi-webapp-staging-${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "BUCKET_NAME=nessi-webapp-prod-${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          else
            echo "Branch not recognized. Exiting."
            exit 1
          fi

      - name: Upload to S3
        run: |
          aws s3 sync ./out s3://$BUCKET_NAME --delete
        env:
          BUCKET_NAME: ${{ env.BUCKET_NAME }}

      - name: Invalidate CloudFront Cache
        run: |
          if [[ "${{ github.ref_name }}" == "dev" ]]; then
            DISTRIBUTION_ID="${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}"
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            DISTRIBUTION_ID="${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGING }}"
          elif [[ "${{ github.ref_name }}" == "main" ]]; then
            DISTRIBUTION_ID="${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }}"
          else
            echo "Branch not recognized. Exiting."
            exit 1
          fi

          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"
