name: Build and Export Next.js App

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then
            aws s3 sync ./out s3://nessi-webapp-dev-203918872163-us-east-2-artifacts --delete;
          elif [ "${{ github.ref_name }}" == "staging" ]; then
            aws s3 sync ./out s3://nessi-webapp-staging-203918872163-us-east-2-artifacts --delete;
          elif [ "${{ github.ref_name }}" == "main" ]; then
            aws s3 sync ./out s3://nessi-webapp-prod-203918872163-us-east-2-artifacts --delete;
          fi

      - name: Trigger Nessi Infra Workflow
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: Nessi-Fishing-Supply/Nessi-Infra
          event-type: deploy-infra
          client-payload: '{"ref": "${{ github.ref }}", "branch": "${{ github.ref_name }}"}'
